(function(){$('.thread-details-tohome').hide();$('.thread-home-c2').each(function(){var c2_cid=$(this).html();var str='';c2_cid=parseInt(c2_cid,10);for(var x in site_group){if(site_group[x].id==c2_cid){str=(function(arr_bnt){var str='';for(var z in arr_bnt){str+='<div><a href="'+_global_js_eb._c_link(arr_bnt[z].id,arr_bnt[z].seo,'s')+'">'+arr_bnt[z].ten+'</a></div>'}return str})(site_group[x].bnt);str+='<div><a href="'+_global_js_eb._c_link(site_group[x].id,site_group[x].seo)+'">Xem th\u00eam '+site_group[x].ten+' &raquo;</a></div>';break}}$(this).html(str)});if(qc_top.length>0){$('#nav').addClass('selected');if(1==1){$('#oi_big_banner').show().html('<img src="'+qc_top[0].img+'" width="'+$('#oi_big_banner').width()+'" />');
var img_height_slide=site_group.length*35;$('#oi_big_banner').css({'line-height':img_height_slide+'px',height:img_height_slide+'px'});$('#oi_big_banner img').load(function(){if(act==''&&qc_top.length>1){var change_banner_first_home=function(x){$('#oi_big_banner').css({'background-image':'url(\''+qc_top[x].img+'\')'}).html('<a href="'+qc_top[x].lnk+'">&nbsp;</a>');setTimeout(function(){x++;if(x>=qc_top.length){x=0}$("#oi_big_banner").animate({opacity:.2},600,function(){change_banner_first_home(x);$("#oi_big_banner").animate({opacity:1},1800)})},5000)};change_banner_first_home(0)}})}else{$('#oi_big_banner').show();var str='',strBtn='',strBtnGo='',strBtnName='',iName=0;for(var i=0;i<qc_top.length;i++){iName=i+1;
strBtnName='button_name'+iName;strBtnGo+=',#'+strBtnName;strBtn+=' <input type="button" value="&nbsp;" id="'+strBtnName+'" />';if(qc_top[i].lnk==''){qc_top[i].lnk=='javascript://';
}str+='<li style="background-image:url(\''+qc_top[i].img+'\')"><a href="'+qc_top[i].lnk+'">&nbsp;</a></li>'}dog('slideshow_in_top','<ul>'+str+'</ul>');setTimeout(function(){var nav_height=$('#nav').height();$('#slideshow_in_top li').css({height:nav_height+'px','line-height':nav_height+'px','background-size':$('#slideshow_in_top').width()+'px auto'});$('#oi_big_banner').css({height:nav_height+'px'});if(qc_top.length>1){dog('slideshowInTop_btn',strBtn);$('#slideshowInTop_btn input:first').addClass('selected');strBtnGo=strBtnGo.substr(1).split(',');setTimeout(function(){$("#slideshow_in_top").jCarouselLite({beforeStart:function(a){},afterEnd:function(a){var pageInTop=a.prevObject.prevObject.length-a.prevObject.length,strBtnName='button_name'+pageInTop;
if(dog(strBtnName)==null){strBtnName='button_name1'}(function(remove,_id,_class){$('#'+remove+' input').removeClass('selected');$('#'+_id).addClass('selected')})('slideshowInTop_btn',strBtnName)},scroll:1,visible:1,start:0,btnGo:strBtnGo,auto:5000,speed:700})},1000)}},100)}}if(qc_event.length>0){for(var i=0;i<qc_event.length;i++){if(qc_event[i].lnk==''){qc_event[i].lnk='javascript://';
}dog('oi_for_ads_event').innerHTML+='<div class="nav-bonus"><a href="'+qc_event[i].lnk+'"><img src="'+qc_event[i].img+'" width="999" /></a></div>'}}if(qc_nav.length>0){var str='',tr='';for(var i=0;i<qc_nav.length;i++){tr='';if(qc_nav[i].lnk==''){qc_nav[i].lnk='javascript://';
}else if(qc_nav[i].lnk.split(location.protocol+'//').length>1){
var a=qc_nav[i].lnk.replace(location.protocol+'//','').replace('.www','').split('/')[0],
b=web_link.replace(location.protocol+'//','').replace('.www','').split('/')[0];
if(a!=b){tr=' target="_blank"'}}str+='<li><a href="'+qc_nav[i].lnk+'"'+tr+'><img src="'+qc_nav[i].img+'" /></a></li>'}$('#oi_for_ads_nav').removeClass('d-none').show().html('<ul class="cf ads-nav">'+str+'</ul>')}$('.set-width-for-home').each(function(){var a=$('.width-for-home-left',this).width(),c=$(this).width(),b=99-(a*100/c);$('.width-for-home-right',this).css({width:b+'%'})})})();